#!/bin/bash
# tests/lib/common.sh — shared fixture helpers, sourced by test scripts.
#
# Provides:
#   IFACE_A / IFACE_B / MAC_GOOD / MAC_BAD / MAC_DST   (design §6 constants)
#   PIN_ROOT / PIN_DIR
#   require_passwordless_sudo → exits 77 (ctest SKIP) if `sudo -n true` fails
#   find_loader               → echoes path of xdpmacfilter binary
#   setup_veth                → fresh ${IFACE_A}/${IFACE_B} pair, both UP
#   cleanup_veth              → wipe veth + pin dir (idempotent, suitable for trap)
#   read_stats <pin>          → echoes "<pass> <drop_deny> <drop_malformed>"
#   wait_for_stats_sum <iface> <expected_sum> [timeout_ms=2000] [poll_ms=20]
#                             → polls stats pin until sum == expected_sum or timeout
#   inject_eth <iface> <src> <dst>            → scapy-based Ethernet frame
#   inject_runt <iface>                       → sub-14-byte raw frame
#   xdp_prog_id <iface>       → echoes attached XDP prog id, empty if none
#
# Env consumed (set by ctest):
#   BUILD_DIR / SOURCE_DIR / TEST_DIR / PINS_SH

set -euo pipefail

# ── Constants per design §6 TestStrategy ──────────────────────────────────
# Per §5.21 C3 (MVP-1.1C): iface names are PID-suffixed to avoid collision
# with any pre-existing host interface (`xdpmf_` project prefix + `$$`).
# setup_veth() preflights for collisions (now scoped INSIDE the per-PID
# netns per §5.25 P1) and errors out if either name is already in use.
IFACE_A=xdpmf_a_$$
IFACE_B=xdpmf_b_$$
MAC_GOOD="02:00:00:00:00:01"
MAC_BAD="02:00:00:00:00:02"
MAC_DST="ff:ff:ff:ff:ff:ff"

# §5.25 P1: per-PID netns owns the veth pair + sysctl mutations.  Pin
# paths stay host-global (bpffs is not netns-isolated in 5.15+, see
# §5.25 "Pin-path host-globalness invariant").  NSEXEC pre-includes
# `sudo -n` — call as `${NSEXEC} <cmd>`, NOT `sudo -n ${NSEXEC} <cmd>`.
#
# Implementation note (Phase-B wrap-bug fix): we use `nsenter --net`
# instead of `ip netns exec` because the latter unshares the mount
# namespace and remounts `/sys` as a fresh per-netns sysfs every
# invocation (iproute2 lib/namespace.c netns_switch() does
# `umount2("/sys", MNT_DETACH)` + `mount(name, "/sys", "sysfs", …)`).
# That side-effect destroys the host bpffs mount at `/sys/fs/bpf`
# inside the netns, contradicting design §5.25 Q1's "Pin-path
# host-globalness invariant" and breaking every loader call.
# `nsenter --net=<path>` enters ONLY the network namespace (mount ns
# of the caller is preserved); host bpffs at `/sys/fs/bpf` remains
# visible exactly as the design intends.
NETNS="xdpmf_ns_$$"
NSEXEC="sudo -n nsenter --net=/var/run/netns/${NETNS}"

# §5.25 P2: PIN_ROOT is generated by CMake from XDPMF_BPFFS_ROOT in
# src/common/mac_filter.h. PINS_SH is passed via ctest TEST_ENV; if
# it is unset, common.sh was sourced outside of ctest.
source "${PINS_SH:?PINS_SH not set — invoke tests via ctest, not directly}"
: "${PIN_ROOT:?PIN_ROOT not set in pins.sh — CMake codegen failed}"
PIN_DIR=${PIN_ROOT}/${IFACE_A}

# ── Passwordless-sudo precondition (per §5.21 C2) ─────────────────────────
# Tests that require root call this near the top after sourcing common.sh.
# On failure (sudo would prompt or be denied), exit 77 — ctest's
# SKIP_RETURN_CODE convention; the test is reported as Skipped, not Failed.
require_passwordless_sudo() {
    if ! sudo -n true 2>/dev/null; then
        echo "SKIP: passwordless sudo not available (sudo -n true failed)" >&2
        echo "      this test needs CAP_BPF/CAP_NET_ADMIN; run ctest as root" >&2
        echo "      or configure NOPASSWD sudo for the test user." >&2
        exit 77
    fi
}

# ── Locate the loader binary in BUILD_DIR ─────────────────────────────────
# §5.26 Q1 R1: binary moved from build/xdpmacfilter (pre-§5.26 implicit
# top-level placement) to build/src/cli/xdpmacfilter (proper add_subdirectory
# layout). Search order keeps the new path first; older paths follow only
# as fallback for partial rebuilds.
find_loader() {
    if [[ -n "${LOADER:-}" && -x "${LOADER}" ]]; then
        printf '%s\n' "${LOADER}"; return 0
    fi
    local cand
    for cand in \
        "${BUILD_DIR}/src/cli/xdpmacfilter" \
        "${BUILD_DIR}/xdpmacfilter" \
        "${BUILD_DIR}/src/loader/xdpmacfilter" \
        "${BUILD_DIR}/loader/xdpmacfilter" \
        "${BUILD_DIR}/bin/xdpmacfilter" \
        "${BUILD_DIR}/src/xdpmacfilter"; do
        if [[ -x "$cand" ]]; then printf '%s\n' "$cand"; return 0; fi
    done
    local found
    found=$(find "${BUILD_DIR}" -maxdepth 5 -type f -executable -name xdpmacfilter 2>/dev/null | head -1 || true)
    if [[ -n "${found}" ]]; then printf '%s\n' "${found}"; return 0; fi
    echo "ERROR: xdpmacfilter binary not found under ${BUILD_DIR}" >&2
    return 1
}

# ── Fixture lifecycle ─────────────────────────────────────────────────────
# Per §5.25 P1 (Option N3): setup_veth owns a per-PID netns ${NETNS} and
# places the veth pair INSIDE it. All sysctl/ifup mutations now hit the
# netns-local copies — host sysctl table untouched. The bpffs pin dir
# ${PIN_DIR} stays host-global because /sys/fs/bpf is not netns-isolated
# on supported kernels (5.15+). cleanup_veth deletes the netns (atomic
# teardown of veth + XDP) plus the bpffs pin dir.
setup_veth() {
    # ── Defensive teardown of leftover state from a crashed prior run ──
    # (a) any stale netns of our exact name (would conflict with `ip
    #     netns add` below); (b) any stale bpffs pin dir for this
    #     IFACE_A. Both are idempotent / swallow ENOENT.
    sudo -n ip netns del "${NETNS}" 2>/dev/null || true
    sudo -n rm -rf "${PIN_DIR}"     2>/dev/null || true

    # Create the per-PID netns; the veth pair lives inside it.
    sudo -n ip netns add "${NETNS}"

    # Per §5.21 C3 preflight, now scoped INSIDE the netns. PID-suffixed
    # names are vanishingly unlikely to collide on a fresh netns, but if
    # they DO (e.g., orphaned by an earlier crashed teardown that
    # somehow lost the netns but kept the iface) we error out loudly
    # rather than silently `ip link del`-ing it.  Honest fixture failure
    # (exit 1), NOT a skip (77).
    if ${NSEXEC} ip link show "${IFACE_A}" >/dev/null 2>&1; then
        echo "ERROR: ${IFACE_A} already exists in netns ${NETNS} — fixture name collision" >&2
        echo "       refusing to clobber; delete it manually if it is stale." >&2
        exit 1
    fi
    if ${NSEXEC} ip link show "${IFACE_B}" >/dev/null 2>&1; then
        echo "ERROR: ${IFACE_B} already exists in netns ${NETNS} — fixture name collision" >&2
        echo "       refusing to clobber; delete it manually if it is stale." >&2
        exit 1
    fi

    ${NSEXEC} ip link add "${IFACE_A}" type veth peer name "${IFACE_B}"

    # Suppress kernel-emitted background traffic on the veth pair so
    # that exact-equality stat assertions are not polluted.  Diagnosis
    # of an earlier failing run: a fresh veth up emits ≈12 IPv6
    # MLDv2/RS/NS/LLMNR frames within the first second.  We:
    #   1) disable IPv6 autoconf BEFORE the iface goes up (so no
    #      link-local address is generated → no DAD, no MLD, no RS),
    #   2) set addrgen mode = none,
    #   3) turn ARP off (raw L2 frames don't need it).
    # All sysctl writes hit the netns-local proc tree (per-netns
    # /proc/sys/net/ipv{4,6}/conf/<iface>/...), so the host's sysctl
    # table is no longer polluted.
    ${NSEXEC} sysctl -w "net.ipv6.conf.${IFACE_A}.disable_ipv6=1" >/dev/null 2>&1 || true
    ${NSEXEC} sysctl -w "net.ipv6.conf.${IFACE_B}.disable_ipv6=1" >/dev/null 2>&1 || true
    ${NSEXEC} ip link set "${IFACE_A}" addrgenmode none 2>/dev/null || true
    ${NSEXEC} ip link set "${IFACE_B}" addrgenmode none 2>/dev/null || true
    ${NSEXEC} ip link set "${IFACE_A}" arp off          2>/dev/null || true
    ${NSEXEC} ip link set "${IFACE_B}" arp off          2>/dev/null || true

    ${NSEXEC} ip link set "${IFACE_A}" up
    ${NSEXEC} ip link set "${IFACE_B}" up

    # Per pack idiom: rp_filter can drop frames before XDP runs.
    ${NSEXEC} sysctl -w "net.ipv4.conf.${IFACE_A}.rp_filter=0" >/dev/null 2>&1 || true
    ${NSEXEC} sysctl -w "net.ipv4.conf.${IFACE_B}.rp_filter=0" >/dev/null 2>&1 || true
    ${NSEXEC} sysctl -w "net.ipv4.conf.all.rp_filter=0"        >/dev/null 2>&1 || true

    # Let any residual chatter quiesce BEFORE XDP attaches; anything
    # that fires now is invisible to the BPF program (not attached yet).
    # Per §5.21 C1 this is a fixture-setup sleep (carrier-up + quiesce),
    # NOT a post-inject synchronization — it stays as-is.
    sleep 0.5
}

cleanup_veth() {
    set +e
    # §5.25 P1: deleting the netns is the atomic teardown of veth pair
    # AND any XDP attachment (the netns owns both). No separate
    # `ip link del` needed. The bpffs pin dir is still host-global, so
    # we remove it explicitly.
    sudo -n ip netns del "${NETNS}" 2>/dev/null
    sudo -n rm -rf "${PIN_DIR}"     2>/dev/null
    set -e
}

# ── Stats reader (delegates to read_stats.py) ─────────────────────────────
# Echoes 3 space-separated u64 counters: pass drop_deny drop_malformed
read_stats() {
    local pin="${1:-${PIN_DIR}/stats}"
    sudo -n python3 "${TEST_DIR}/lib/read_stats.py" "${pin}"
}

# ── Stats-sum poll helper (per §5.21 C1, MVP-1.1C) ───────────────────────
# Polls the pinned stats map until the SUM of all 3 counters equals
# expected_sum or until timeout.  Replaces post-inject `sleep 0.3` /
# `sleep 0.5` callsites — tighter loop, deterministic on fast hosts,
# fail-fast on slow hosts.
#
# Usage: wait_for_stats_sum <iface> <expected_sum> [timeout_ms=2000] [poll_ms=20]
# Returns: 0 on match, 1 on timeout.
wait_for_stats_sum() {
    local iface="$1" expected="$2"
    local timeout_ms="${3:-2000}" poll_ms="${4:-20}"
    local pin="${PIN_ROOT}/${iface}/stats"
    local waited_ms=0
    local p d m sum
    while (( waited_ms < timeout_ms )); do
        if read -r p d m < <(sudo -n python3 "${TEST_DIR}/lib/read_stats.py" "${pin}" 2>/dev/null); then
            sum=$(( p + d + m ))
            if (( sum == expected )); then
                return 0
            fi
        fi
        sleep "$(awk -v ms="${poll_ms}" 'BEGIN{printf "%.3f", ms/1000.0}')"
        waited_ms=$(( waited_ms + poll_ms ))
    done
    return 1
}

# ── Frame injection (scapy / raw AF_PACKET) ──────────────────────────────
# Per §5.25 P1: python3 is spawned via `ip netns exec` so the
# AF_PACKET socket opened inside the interpreter binds inside the netns
# where the iface lives (setns(2) happens before exec; child inherits).
# inject_eth <iface> <src_mac> <dst_mac>
inject_eth() {
    local iface="$1" src="$2" dst="$3"
    ${NSEXEC} python3 "${TEST_DIR}/inject/inject_eth.py" "${iface}" "${src}" "${dst}"
}

# inject_runt <iface> — sub-14-byte frame for malformed-frame test.
inject_runt() {
    local iface="$1"
    ${NSEXEC} python3 "${TEST_DIR}/inject/inject_runt.py" "${iface}"
}

# ── XDP-on-iface query ────────────────────────────────────────────────────
# Echoes the attached XDP prog id, or empty string if none.
# Per §5.25 P1: iface lives inside ${NETNS}, so `ip link show` must run
# there too.
xdp_prog_id() {
    local iface="$1"
    ${NSEXEC} ip -j link show "${iface}" 2>/dev/null | jq -r '
        .[0]
        | (.xdp.prog.id // .xdp.attached[]?.prog.id // empty)
    ' | head -n1
}

# ── BPF prog count snapshot (kept for legacy use) ────────────────────────
# Per §5.21 C4, the §6.6 baseline/final clause is dropped — this helper
# is no longer the §6.6 ownership signal (per-iface xdp_prog_id is).
# Retained for any out-of-tree or diagnostic use.
prog_count() {
    sudo -n bpftool prog show --json 2>/dev/null | jq 'length'
}

# ── §5.26 MVP-3.1 helpers ────────────────────────────────────────────────
# apply_config <path-to-yaml> <iface> [extra-args...]
#   Thin wrapper that invokes the loader's `apply` subcommand inside the
#   per-PID netns. Same NSEXEC discipline as inject_eth / xdp_prog_id —
#   the iface lives in ${NETNS} so we must enter the netns to address it.
#   Returns the loader's exit code untouched (so tests can assert rc==9
#   on ConfigError, rc==0 on success, etc.).
apply_config() {
    local config_path="$1" iface="$2"
    shift 2
    ${NSEXEC} "$(find_loader)" apply -f "${config_path}" --iface "${iface}" "$@"
}

# wait_for_active_idx_flip <iface> <expected> [timeout_ms=2000] [poll_ms=20]
#   Polls bpftool's dump of the per-iface active_idx pin until the slot-0
#   value matches `expected`. Returns 0 on match, 1 on timeout.
#   Used by §6.23 / §6.24 / §6.25 to observe the atomic swap commit.
wait_for_active_idx_flip() {
    local iface="$1" expected="$2"
    local timeout_ms="${3:-2000}" poll_ms="${4:-20}"
    local pin="${PIN_ROOT}/${iface}/active_idx"
    local waited_ms=0 cur
    while (( waited_ms < timeout_ms )); do
        cur=$(sudo -n bpftool map dump pinned "${pin}" -j 2>/dev/null \
              | jq -r '.[0].formatted.value // .[0].value[0] // .[0].value' 2>/dev/null || true)
        if [[ "${cur}" == "${expected}" ]]; then
            return 0
        fi
        sleep "$(awk -v ms="${poll_ms}" 'BEGIN{printf "%.3f", ms/1000.0}')"
        waited_ms=$(( waited_ms + poll_ms ))
    done
    return 1
}

# kill_loader_keep_link <iface>
#   Sends SIGKILL to any lingering xdpmacfilter process AFTER the apply has
#   pinned the link. P0a's contract is the link survives loader-process
#   termination — this helper makes the test explicit. In practice the
#   `apply` invocation has already exited by the time the test reaches the
#   step, so this is belt-and-suspenders (per §6.25 step 10). ENOENT-safe.
kill_loader_keep_link() {
    local iface="$1"
    sudo -n pkill -9 -f "xdpmacfilter.*${iface}" 2>/dev/null || true
}
