#!/bin/bash
# tests/lib/common.sh — shared fixture helpers, sourced by test scripts.
#
# Provides:
#   IFACE_A / IFACE_B / MAC_GOOD / MAC_BAD / MAC_DST   (design §6 constants)
#   PIN_ROOT / PIN_DIR
#   require_passwordless_sudo → exits 77 (ctest SKIP) if `sudo -n true` fails
#   find_loader               → echoes path of xdpfilter binary
#   setup_veth                → fresh ${IFACE_A}/${IFACE_B} pair, both UP
#   cleanup_veth              → wipe veth + pin dir (idempotent, suitable for trap)
#   read_stats <pin>          → echoes "<pass> <drop_deny> <drop_malformed>"
#   wait_for_stats_sum <iface> <expected_sum> [timeout_ms=2000] [poll_ms=20]
#                             → polls stats pin until sum == expected_sum or timeout
#   inject_eth <iface> <src> <dst>            → scapy-based Ethernet frame
#   inject_runt <iface>                       → sub-14-byte raw frame
#   xdp_prog_id <iface>       → echoes attached XDP prog id, empty if none
#
# Env consumed (set by ctest):
#   BUILD_DIR / SOURCE_DIR / TEST_DIR / PINS_SH

set -euo pipefail

# ── Constants per design §6 TestStrategy ──────────────────────────────────
# Per §5.21 C3 (MVP-1.1C): iface names are PID-suffixed to avoid collision
# with any pre-existing host interface (`xdpmf_` project prefix + `$$`).
# setup_veth() preflights for collisions (now scoped INSIDE the per-PID
# netns per §5.25 P1) and errors out if either name is already in use.
IFACE_A=xdpmf_a_$$
IFACE_B=xdpmf_b_$$
MAC_GOOD="02:00:00:00:00:01"
MAC_BAD="02:00:00:00:00:02"
MAC_DST="ff:ff:ff:ff:ff:ff"

# §5.75 (MVP-4.35 / B42): the redirect delivery oracle needs a SECOND veth
# pair in the SAME ${NETNS}. xdpfilter redirects matched traffic OUT IFACE_C
# (devmap[0]=ifindex(IFACE_C)); a frame egressing IFACE_C arrives RX on its
# peer IFACE_D where the counting sink (sink_xdp.bpf.o) runs. These names are
# DEFINED for every test but the pair is only CREATED by the opt-in
# setup_redirect_sink() helper, so the 60+ pre-§5.75 ctests run in a
# byte-identical single-pair topology (PI-mvp-4.35-VERDICT-IDENTITY — do not
# perturb the existing corpus's fixture environment).
IFACE_C=xdpmf_c_$$
IFACE_D=xdpmf_d_$$

# §5.25 P1: per-PID netns owns the veth pair + sysctl mutations.  Pin
# paths stay host-global (bpffs is not netns-isolated in 5.15+, see
# §5.25 "Pin-path host-globalness invariant").  NSEXEC pre-includes
# `sudo -n` — call as `${NSEXEC} <cmd>`, NOT `sudo -n ${NSEXEC} <cmd>`.
#
# Implementation note (Phase-B wrap-bug fix): we use `nsenter --net`
# instead of `ip netns exec` because the latter unshares the mount
# namespace and remounts `/sys` as a fresh per-netns sysfs every
# invocation (iproute2 lib/namespace.c netns_switch() does
# `umount2("/sys", MNT_DETACH)` + `mount(name, "/sys", "sysfs", …)`).
# That side-effect destroys the host bpffs mount at `/sys/fs/bpf`
# inside the netns, contradicting design §5.25 Q1's "Pin-path
# host-globalness invariant" and breaking every loader call.
# `nsenter --net=<path>` enters ONLY the network namespace (mount ns
# of the caller is preserved); host bpffs at `/sys/fs/bpf` remains
# visible exactly as the design intends.
NETNS="xdpmf_ns_$$"
NSEXEC="sudo -n nsenter --net=/var/run/netns/${NETNS}"

# §5.25 P2: PIN_ROOT is generated by CMake from XDPMF_BPFFS_ROOT in
# src/common/xdpfilter.h. PINS_SH is passed via ctest TEST_ENV; if
# it is unset, common.sh was sourced outside of ctest.
source "${PINS_SH:?PINS_SH not set — invoke tests via ctest, not directly}"
: "${PIN_ROOT:?PIN_ROOT not set in pins.sh — CMake codegen failed}"
PIN_DIR=${PIN_ROOT}/${IFACE_A}
# §5.75: bpffs dir holding the sink program + its pinned `sink_count` map
# (PID-scoped so concurrent ctest -jN runs never collide). Removed by
# cleanup_veth alongside PIN_DIR.
SINK_DIR=${PIN_ROOT}/sink_${IFACE_A}

# ── Passwordless-sudo precondition (per §5.21 C2) ─────────────────────────
# Tests that require root call this near the top after sourcing common.sh.
# On failure (sudo would prompt or be denied), exit 77 — ctest's
# SKIP_RETURN_CODE convention; the test is reported as Skipped, not Failed.
require_passwordless_sudo() {
    # CI build-only gate (§5.72 / B39): a hosted runner has passwordless sudo
    # but cannot reliably create veth/netns + attach XDP. When XDPMF_CI_BUILD_ONLY=1
    # the privileged datapath suite SKIPs (77) DETERMINISTICALLY — its real
    # verification lives on the local/self-hosted mint gate. This reverses the
    # §5.63 D-mvp-4.23 full-coverage-on-CI intent (see §5.72); the non-privileged
    # tests (compile, insn-gate, golden-stderr, config/CLI) still RUN and gate.
    if [ "${XDPMF_CI_BUILD_ONLY:-0}" = "1" ]; then
        echo "SKIP: XDPMF_CI_BUILD_ONLY=1 — privileged datapath suite deferred to the local/self-hosted gate" >&2
        exit 77
    fi
    if ! sudo -n true 2>/dev/null; then
        echo "SKIP: passwordless sudo not available (sudo -n true failed)" >&2
        echo "      this test needs CAP_BPF/CAP_NET_ADMIN; run ctest as root" >&2
        echo "      or configure NOPASSWD sudo for the test user." >&2
        exit 77
    fi
}

# ── Locate the loader binary in BUILD_DIR ─────────────────────────────────
# §5.26 Q1 R1: binary moved from build/xdpfilter (pre-§5.26 implicit
# top-level placement) to build/src/cli/xdpfilter (proper add_subdirectory
# layout). Search order keeps the new path first; older paths follow only
# as fallback for partial rebuilds.
find_loader() {
    if [[ -n "${LOADER:-}" && -x "${LOADER}" ]]; then
        printf '%s\n' "${LOADER}"; return 0
    fi
    local cand
    for cand in \
        "${BUILD_DIR}/src/cli/xdpfilter" \
        "${BUILD_DIR}/xdpfilter" \
        "${BUILD_DIR}/src/loader/xdpfilter" \
        "${BUILD_DIR}/loader/xdpfilter" \
        "${BUILD_DIR}/bin/xdpfilter" \
        "${BUILD_DIR}/src/xdpfilter"; do
        if [[ -x "$cand" ]]; then printf '%s\n' "$cand"; return 0; fi
    done
    local found
    found=$(find "${BUILD_DIR}" -maxdepth 5 -type f -executable -name xdpfilter 2>/dev/null | head -1 || true)
    if [[ -n "${found}" ]]; then printf '%s\n' "${found}"; return 0; fi
    echo "ERROR: xdpfilter binary not found under ${BUILD_DIR}" >&2
    return 1
}

# ── Fixture lifecycle ─────────────────────────────────────────────────────
# Per §5.25 P1 (Option N3): setup_veth owns a per-PID netns ${NETNS} and
# places the veth pair INSIDE it. All sysctl/ifup mutations now hit the
# netns-local copies — host sysctl table untouched. The bpffs pin dir
# ${PIN_DIR} stays host-global because /sys/fs/bpf is not netns-isolated
# on supported kernels (5.15+). cleanup_veth deletes the netns (atomic
# teardown of veth + XDP) plus the bpffs pin dir.
setup_veth() {
    # ── Defensive teardown of leftover state from a crashed prior run ──
    # (a) any stale netns of our exact name (would conflict with `ip
    #     netns add` below); (b) any stale bpffs pin dir for this
    #     IFACE_A. Both are idempotent / swallow ENOENT.
    sudo -n ip netns del "${NETNS}" 2>/dev/null || true
    sudo -n rm -rf "${PIN_DIR}"     2>/dev/null || true

    # Create the per-PID netns; the veth pair lives inside it.
    sudo -n ip netns add "${NETNS}"

    # Per §5.21 C3 preflight, now scoped INSIDE the netns. PID-suffixed
    # names are vanishingly unlikely to collide on a fresh netns, but if
    # they DO (e.g., orphaned by an earlier crashed teardown that
    # somehow lost the netns but kept the iface) we error out loudly
    # rather than silently `ip link del`-ing it.  Honest fixture failure
    # (exit 1), NOT a skip (77).
    if ${NSEXEC} ip link show "${IFACE_A}" >/dev/null 2>&1; then
        echo "ERROR: ${IFACE_A} already exists in netns ${NETNS} — fixture name collision" >&2
        echo "       refusing to clobber; delete it manually if it is stale." >&2
        exit 1
    fi
    if ${NSEXEC} ip link show "${IFACE_B}" >/dev/null 2>&1; then
        echo "ERROR: ${IFACE_B} already exists in netns ${NETNS} — fixture name collision" >&2
        echo "       refusing to clobber; delete it manually if it is stale." >&2
        exit 1
    fi

    ${NSEXEC} ip link add "${IFACE_A}" type veth peer name "${IFACE_B}"

    # Suppress kernel-emitted background traffic on the veth pair so
    # that exact-equality stat assertions are not polluted.  Diagnosis
    # of an earlier failing run: a fresh veth up emits ≈12 IPv6
    # MLDv2/RS/NS/LLMNR frames within the first second.  We:
    #   1) disable IPv6 autoconf BEFORE the iface goes up (so no
    #      link-local address is generated → no DAD, no MLD, no RS),
    #   2) set addrgen mode = none,
    #   3) turn ARP off (raw L2 frames don't need it).
    # All sysctl writes hit the netns-local proc tree (per-netns
    # /proc/sys/net/ipv{4,6}/conf/<iface>/...), so the host's sysctl
    # table is no longer polluted.
    ${NSEXEC} sysctl -w "net.ipv6.conf.${IFACE_A}.disable_ipv6=1" >/dev/null 2>&1 || true
    ${NSEXEC} sysctl -w "net.ipv6.conf.${IFACE_B}.disable_ipv6=1" >/dev/null 2>&1 || true
    ${NSEXEC} ip link set "${IFACE_A}" addrgenmode none 2>/dev/null || true
    ${NSEXEC} ip link set "${IFACE_B}" addrgenmode none 2>/dev/null || true
    ${NSEXEC} ip link set "${IFACE_A}" arp off          2>/dev/null || true
    ${NSEXEC} ip link set "${IFACE_B}" arp off          2>/dev/null || true

    ${NSEXEC} ip link set "${IFACE_A}" up
    ${NSEXEC} ip link set "${IFACE_B}" up

    # Per pack idiom: rp_filter can drop frames before XDP runs.
    ${NSEXEC} sysctl -w "net.ipv4.conf.${IFACE_A}.rp_filter=0" >/dev/null 2>&1 || true
    ${NSEXEC} sysctl -w "net.ipv4.conf.${IFACE_B}.rp_filter=0" >/dev/null 2>&1 || true
    ${NSEXEC} sysctl -w "net.ipv4.conf.all.rp_filter=0"        >/dev/null 2>&1 || true

    # Let any residual chatter quiesce BEFORE XDP attaches; anything
    # that fires now is invisible to the BPF program (not attached yet).
    # Per §5.21 C1 this is a fixture-setup sleep (carrier-up + quiesce),
    # NOT a post-inject synchronization — it stays as-is.
    sleep 0.5
}

cleanup_veth() {
    set +e
    # §5.25 P1: deleting the netns is the atomic teardown of veth pair
    # AND any XDP attachment (the netns owns both). No separate
    # `ip link del` needed. The bpffs pin dir is still host-global, so
    # we remove it explicitly.
    sudo -n ip netns del "${NETNS}" 2>/dev/null
    sudo -n rm -rf "${PIN_DIR}"     2>/dev/null
    # §5.75: the sink prog/map pin dir is host-global like PIN_DIR (bpffs is
    # not netns-isolated). Idempotent — absent for every non-redirect test.
    sudo -n rm -rf "${SINK_DIR}"    2>/dev/null
    set -e
}

# ── §5.75 (MVP-4.35 / B42) redirect delivery-oracle harness ───────────────
# setup_redirect_sink — OPT-IN extension called AFTER setup_veth by the
# T_REDIRECT_* tests. Creates the second veth pair (IFACE_C/IFACE_D) inside
# the SAME ${NETNS} and loads+pins+attaches the counting sink on IFACE_D.
# Topology: production filter on IFACE_A (inject on IFACE_B → RX on IFACE_A);
# redirect target = IFACE_C; sink on IFACE_D (the peer) counts delivered
# frames. Pre-§5.75 tests never call this → their environment is unchanged.
#
# Requires: ${BUILD_DIR}/sink_xdp.bpf.o (add_bpf_object sink_xdp). If the
# object is missing the caller should treat it as a build-gap FAIL, not a
# silent skip — the delivery oracle cannot run without it.
setup_redirect_sink() {
    local sink_obj="${BUILD_DIR}/sink_xdp.bpf.o"
    if [[ ! -f "${sink_obj}" ]]; then
        echo "FAIL: sink object missing at ${sink_obj} (build add_bpf_object sink_xdp)" >&2
        return 1
    fi

    # Defensive wipe of any stale sink pin dir from a crashed prior run.
    sudo -n rm -rf "${SINK_DIR}" 2>/dev/null || true

    # Second veth pair, same quiesce discipline as the A/B pair (IPv6 off,
    # addrgen none, arp off) so no kernel-emitted frames pollute the sink.
    ${NSEXEC} ip link add "${IFACE_C}" type veth peer name "${IFACE_D}"
    ${NSEXEC} sysctl -w "net.ipv6.conf.${IFACE_C}.disable_ipv6=1" >/dev/null 2>&1 || true
    ${NSEXEC} sysctl -w "net.ipv6.conf.${IFACE_D}.disable_ipv6=1" >/dev/null 2>&1 || true
    ${NSEXEC} ip link set "${IFACE_C}" addrgenmode none 2>/dev/null || true
    ${NSEXEC} ip link set "${IFACE_D}" addrgenmode none 2>/dev/null || true
    ${NSEXEC} ip link set "${IFACE_C}" arp off           2>/dev/null || true
    ${NSEXEC} ip link set "${IFACE_D}" arp off           2>/dev/null || true
    ${NSEXEC} ip link set "${IFACE_C}" up
    ${NSEXEC} ip link set "${IFACE_D}" up

    # The sink prog/map pin dir lives on the host-global bpffs root, which
    # the loader normally creates on apply. Create it here (apply may run
    # after this helper) so `bpftool prog loadall` has a parent to pin into.
    sudo -n mkdir -p "${PIN_ROOT}" 2>/dev/null || true

    # Load + pin prog AND maps under ${SINK_DIR}; attach the pinned prog on
    # IFACE_D in generic mode (XDP RX path on the target's peer must be live
    # for the redirected frame to be counted). bpftool creates ${SINK_DIR}.
    sudo -n bpftool prog loadall "${sink_obj}" "${SINK_DIR}" type xdp \
        pinmaps "${SINK_DIR}"
    ${NSEXEC} ip link set "${IFACE_D}" xdpgeneric pinned "${SINK_DIR}/sink_count_prog"
    sleep 0.2
}

# read_sink [pin] — echoes the summed (across CPUs) key-0 value of the sink's
# pinned PERCPU_ARRAY counter. Reuses read_stats.py (column 0 == the key-0
# sum for a single-entry map), mirroring read_stats's bpftool/percpu plumbing.
read_sink() {
    local pin="${1:-${SINK_DIR}/sink_count}"
    sudo -n python3 "${TEST_DIR}/lib/read_stats.py" "${pin}" 2>/dev/null \
        | awk '{print $1+0}'
}

# ifindex_of <iface> — echoes the kernel ifindex of an iface inside ${NETNS}
# (the devmap[0] value the loader writes for steering.redirect_to == that
# iface). Empty if the iface does not resolve.
#
# NB: we read the ifindex via `ip -o link show` (the leading "<N>:" field),
# NOT via /sys/class/net/<iface>/ifindex — `nsenter --net=<ns>` enters ONLY
# the network namespace and does NOT re-associate sysfs, so the per-netns
# /sys/class/net/<iface> nodes are NOT visible (ENOENT). `ip` queries the
# ifindex over netlink inside the netns, which works.
ifindex_of() {
    local iface="$1"
    ${NSEXEC} ip -o link show "${iface}" 2>/dev/null \
        | awk -F: '{print $1}' | tr -d '[:space:]'
}

# §5.75 5-column stats reader — pass drop_deny drop_malformed pass_cidr
# redirect. Parallel sibling of read_stats_with_cidr; the existing 3-/4-column
# helpers stay UNCHANGED for the pre-§5.75 ctests (PI-mvp-4.35-VERDICT-IDENTITY).
read_stats_with_redirect() {
    local pin="${1:-${PIN_DIR}/stats}"
    sudo -n python3 "${TEST_DIR}/lib/read_stats.py" --include-redirect "${pin}"
}

# §5.75 parallel sibling of wait_for_stats_sum: sums all 5 counters
# (pass + drop_deny + drop_malformed + pass_cidr + redirect). Used by the
# T_REDIRECT_* tests; the 3-/4-column waiters stay UNCHANGED.
wait_for_stats_sum_with_redirect() {
    local iface="$1" expected="$2"
    local timeout_ms="${3:-2000}" poll_ms="${4:-20}"
    local pin="${PIN_ROOT}/${iface}/stats"
    local waited_ms=0
    local p d m c r sum
    while (( waited_ms < timeout_ms )); do
        if read -r p d m c r < <(sudo -n python3 "${TEST_DIR}/lib/read_stats.py" --include-redirect "${pin}" 2>/dev/null); then
            sum=$(( p + d + m + c + r ))
            if (( sum == expected )); then
                return 0
            fi
        fi
        sleep "$(awk -v ms="${poll_ms}" 'BEGIN{printf "%.3f", ms/1000.0}')"
        waited_ms=$(( waited_ms + poll_ms ))
    done
    return 1
}

# wait_for_sink <expected> [timeout_ms=2000] [poll_ms=20] — poll the sink
# counter until it reaches >= expected or timeout. Returns 0 on match.
wait_for_sink() {
    local expected="$1"
    local timeout_ms="${2:-2000}" poll_ms="${3:-20}"
    local waited_ms=0 cur
    while (( waited_ms < timeout_ms )); do
        cur=$(read_sink)
        if [[ -n "${cur}" ]] && (( cur >= expected )); then
            return 0
        fi
        sleep "$(awk -v ms="${poll_ms}" 'BEGIN{printf "%.3f", ms/1000.0}')"
        waited_ms=$(( waited_ms + poll_ms ))
    done
    return 1
}

# ── Stats reader (delegates to read_stats.py) ─────────────────────────────
# Echoes 3 space-separated u64 counters: pass drop_deny drop_malformed
read_stats() {
    local pin="${1:-${PIN_DIR}/stats}"
    sudo -n python3 "${TEST_DIR}/lib/read_stats.py" "${pin}"
}

# §5.27 (MVP-3.2): 4-column stats reader — pass drop_deny drop_malformed pass_cidr.
# Layered ON TOP of read_stats() to preserve PI-13-3.2 back-compat (existing
# callers continue to see the 3-column shape).
read_stats_with_cidr() {
    local pin="${1:-${PIN_DIR}/stats}"
    sudo -n python3 "${TEST_DIR}/lib/read_stats.py" --include-pass-cidr "${pin}"
}

# ── Stats-sum poll helper (per §5.21 C1, MVP-1.1C) ───────────────────────
# Polls the pinned stats map until the SUM of all 3 counters equals
# expected_sum or until timeout.  Replaces post-inject `sleep 0.3` /
# `sleep 0.5` callsites — tighter loop, deterministic on fast hosts,
# fail-fast on slow hosts.
#
# Usage: wait_for_stats_sum <iface> <expected_sum> [timeout_ms=2000] [poll_ms=20]
# Returns: 0 on match, 1 on timeout.
wait_for_stats_sum() {
    local iface="$1" expected="$2"
    local timeout_ms="${3:-2000}" poll_ms="${4:-20}"
    local pin="${PIN_ROOT}/${iface}/stats"
    local waited_ms=0
    local p d m sum
    while (( waited_ms < timeout_ms )); do
        if read -r p d m < <(sudo -n python3 "${TEST_DIR}/lib/read_stats.py" "${pin}" 2>/dev/null); then
            sum=$(( p + d + m ))
            if (( sum == expected )); then
                return 0
            fi
        fi
        sleep "$(awk -v ms="${poll_ms}" 'BEGIN{printf "%.3f", ms/1000.0}')"
        waited_ms=$(( waited_ms + poll_ms ))
    done
    return 1
}

# §5.27 (MVP-3.2) parallel sibling of wait_for_stats_sum: sums all 4 counters
# (pass + drop_deny + drop_malformed + pass_cidr). Used by §6.28-§6.31 CIDR
# tests; existing wait_for_stats_sum stays UNCHANGED for the 27 pre-§5.27 ctests.
wait_for_stats_sum_with_cidr() {
    local iface="$1" expected="$2"
    local timeout_ms="${3:-2000}" poll_ms="${4:-20}"
    local pin="${PIN_ROOT}/${iface}/stats"
    local waited_ms=0
    local p d m c sum
    while (( waited_ms < timeout_ms )); do
        if read -r p d m c < <(sudo -n python3 "${TEST_DIR}/lib/read_stats.py" --include-pass-cidr "${pin}" 2>/dev/null); then
            sum=$(( p + d + m + c ))
            if (( sum == expected )); then
                return 0
            fi
        fi
        sleep "$(awk -v ms="${poll_ms}" 'BEGIN{printf "%.3f", ms/1000.0}')"
        waited_ms=$(( waited_ms + poll_ms ))
    done
    return 1
}

# ── §5.61 (MVP-4.21 / B30) operator-id → internal-slot remap ─────────────
# Post-B30 the raw `rule_counters` / `rules_inner` BPF maps are SLOT-keyed
# (slot = a rule's rank in ascending-unique-id order), decoupled from the
# operator `id`. A test that peeks those maps BY OPERATOR ID must first
# resolve id->slot through the `slot_rule_id` pin's active/selected half —
# exactly as the production exporter does (design.md §5.61 EDIT-1 /
# D-mvp-4.21-RAWMAP-REMAP). These helpers centralise that remap.
#
# active_idx_of <iface> → echoes the shared active_idx value (0|1) or empty.
active_idx_of() {
    local iface="$1"
    local raw v hex
    raw=$(sudo -n bpftool map dump pinned "${PIN_ROOT}/${iface}/active_idx" --json 2>/dev/null)
    [[ -z "${raw}" ]] && return
    v=$(printf '%s' "${raw}" | jq -r '.[0].formatted.value // empty' 2>/dev/null)
    if [[ -n "${v}" && "${v}" != "null" ]]; then echo "${v}"; return; fi
    hex=$(printf '%s' "${raw}" | jq -r '.[0].value[0] // empty' 2>/dev/null | sed 's/^0x//')
    if [[ -n "${hex}" && "${hex}" != "null" ]]; then printf '%d\n' "0x${hex}"; fi
}

# half_of_pin <pin> → echoes 0 for a *_a pin, 1 for a *_b pin (the shared
# active_idx governs ALL parallel-outer maps uniformly, so the _a/_b suffix
# of ANY parallel pin names its ruleset half). Empty if neither suffix.
half_of_pin() {
    case "$1" in
        *_a) echo 0 ;;
        *_b) echo 1 ;;
        *)   return 1 ;;
    esac
}

# id_to_slot <iface> <id> [half] → echoes the slot holding operator <id> in
# ruleset half <half> (default = active half), or EMPTY if that id is not
# loaded in that half. Reads the slot_rule_id pin (delegates to id_to_slot.py).
id_to_slot() {
    local iface="$1" id="$2" half="${3:-}"
    if [[ -z "${half}" ]]; then half=$(active_idx_of "${iface}"); fi
    [[ -z "${half}" ]] && return
    sudo -n python3 "${TEST_DIR}/lib/id_to_slot.py" \
        "${PIN_ROOT}/${iface}/slot_rule_id" "${half}" "${id}" 2>/dev/null
}

# read_rule_counter_by_id <iface> <counter_inner_pin> <id>
#   Resolves <id> -> slot (half inferred from the inner pin's _a/_b suffix,
#   falling back to the active half) and reads that slot's counter. Echoes 0
#   if the id is not present in that half (an unloaded rule has no counter).
read_rule_counter_by_id() {
    local iface="$1" pin="$2" id="$3" half slot
    half=$(half_of_pin "${pin}") || half=$(active_idx_of "${iface}")
    slot=$(id_to_slot "${iface}" "${id}" "${half}")
    [[ -z "${slot}" ]] && { echo 0; return; }
    sudo -n python3 "${TEST_DIR}/lib/read_rule_counters.py" "${pin}" "${slot}"
}

# ── Frame injection (scapy / raw AF_PACKET) ──────────────────────────────
# Per §5.25 P1: python3 is spawned via `ip netns exec` so the
# AF_PACKET socket opened inside the interpreter binds inside the netns
# where the iface lives (setns(2) happens before exec; child inherits).
# inject_eth <iface> <src_mac> <dst_mac>
inject_eth() {
    local iface="$1" src="$2" dst="$3"
    ${NSEXEC} python3 "${TEST_DIR}/inject/inject_eth.py" "${iface}" "${src}" "${dst}"
}

# inject_runt <iface> — sub-14-byte frame for malformed-frame test.
inject_runt() {
    local iface="$1"
    ${NSEXEC} python3 "${TEST_DIR}/inject/inject_runt.py" "${iface}"
}

# ── XDP-on-iface query ────────────────────────────────────────────────────
# Echoes the attached XDP prog id, or empty string if none.
# Per §5.25 P1: iface lives inside ${NETNS}, so `ip link show` must run
# there too.
xdp_prog_id() {
    local iface="$1"
    ${NSEXEC} ip -j link show "${iface}" 2>/dev/null | jq -r '
        .[0]
        | (.xdp.prog.id // .xdp.attached[]?.prog.id // empty)
    ' | head -n1
}

# ── BPF prog count snapshot (kept for legacy use) ────────────────────────
# Per §5.21 C4, the §6.6 baseline/final clause is dropped — this helper
# is no longer the §6.6 ownership signal (per-iface xdp_prog_id is).
# Retained for any out-of-tree or diagnostic use.
prog_count() {
    sudo -n bpftool prog show --json 2>/dev/null | jq 'length'
}

# ── §5.26 MVP-3.1 helpers ────────────────────────────────────────────────
# apply_config <path-to-yaml> <iface> [extra-args...]
#   Thin wrapper that invokes the loader's `apply` subcommand inside the
#   per-PID netns. Same NSEXEC discipline as inject_eth / xdp_prog_id —
#   the iface lives in ${NETNS} so we must enter the netns to address it.
#   Returns the loader's exit code untouched (so tests can assert rc==9
#   on ConfigError, rc==0 on success, etc.).
apply_config() {
    local config_path="$1" iface="$2"
    shift 2
    ${NSEXEC} "$(find_loader)" apply -f "${config_path}" --iface "${iface}" "$@"
}

# wait_for_active_idx_flip <iface> <expected> [timeout_ms=2000] [poll_ms=20]
#   Polls bpftool's dump of the per-iface active_idx pin until the slot-0
#   value matches `expected`. Returns 0 on match, 1 on timeout.
#   Used by §6.23 / §6.24 / §6.25 to observe the atomic swap commit.
wait_for_active_idx_flip() {
    local iface="$1" expected="$2"
    local timeout_ms="${3:-2000}" poll_ms="${4:-20}"
    local pin="${PIN_ROOT}/${iface}/active_idx"
    local waited_ms=0 cur
    while (( waited_ms < timeout_ms )); do
        cur=$(sudo -n bpftool map dump pinned "${pin}" -j 2>/dev/null \
              | jq -r '.[0].formatted.value // .[0].value[0] // .[0].value' 2>/dev/null || true)
        if [[ "${cur}" == "${expected}" ]]; then
            return 0
        fi
        sleep "$(awk -v ms="${poll_ms}" 'BEGIN{printf "%.3f", ms/1000.0}')"
        waited_ms=$(( waited_ms + poll_ms ))
    done
    return 1
}

# kill_loader_keep_link <iface>
#   Sends SIGKILL to any lingering xdpfilter process AFTER the apply has
#   pinned the link. P0a's contract is the link survives loader-process
#   termination — this helper makes the test explicit. In practice the
#   `apply` invocation has already exited by the time the test reaches the
#   step, so this is belt-and-suspenders (per §6.25 step 10). ENOENT-safe.
kill_loader_keep_link() {
    local iface="$1"
    sudo -n pkill -9 -f "xdpfilter.*${iface}" 2>/dev/null || true
}
